import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import { resolve } from 'node:path';
import { tokenize } from '../src/utils/tokensize'

describe.only('parser', async () => {

  const id = resolve(__dirname, './fixtures/source.js')
  const code = await fs.promises.readFile(id, 'utf-8')

  it('should be parser to Tooken', () => {

    expect(tokenize(code)).toMatchInlineSnapshot(`
      [
        {
          "col": 7,
          "row": 0,
          "start": 0,
          "state": 1,
          "type": "Keyword",
          "value": "function",
        },
        {
          "col": 11,
          "row": 0,
          "start": 9,
          "state": 2,
          "type": "Identifier",
          "value": "add",
        },
        {
          "col": 12,
          "row": 0,
          "start": 12,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 13,
          "row": 0,
          "start": 13,
          "state": 2,
          "type": "Identifier",
          "value": "a",
        },
        {
          "col": 14,
          "row": 0,
          "start": 14,
          "state": 4,
          "type": "Punctuator",
          "value": ",",
        },
        {
          "col": 16,
          "row": 0,
          "start": 16,
          "state": 2,
          "type": "Identifier",
          "value": "b",
        },
        {
          "col": 17,
          "row": 0,
          "start": 17,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 19,
          "row": 0,
          "start": 19,
          "state": 4,
          "type": "Punctuator",
          "value": "{",
        },
        {
          "col": 21,
          "row": 0,
          "start": 20,
          "state": 5,
          "type": "Punctuator",
          "value": "rn",
        },
        {
          "col": 4,
          "row": 1,
          "start": 2,
          "state": 1,
          "type": "Keyword",
          "value": "let",
        },
        {
          "col": 6,
          "row": 1,
          "start": 6,
          "state": 2,
          "type": "Identifier",
          "value": "a",
        },
        {
          "col": 8,
          "row": 1,
          "start": 8,
          "state": 6,
          "type": "Operators",
          "value": "=",
        },
        {
          "col": 10,
          "row": 1,
          "start": 10,
          "state": 3,
          "type": "Number",
          "value": "1",
        },
        {
          "col": 12,
          "row": 1,
          "start": 11,
          "state": 5,
          "type": "Punctuator",
          "value": "rn",
        },
        {
          "col": 4,
          "row": 2,
          "start": 2,
          "state": 1,
          "type": "Keyword",
          "value": "for",
        },
        {
          "col": 6,
          "row": 2,
          "start": 6,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 9,
          "row": 2,
          "start": 7,
          "state": 1,
          "type": "Keyword",
          "value": "let",
        },
        {
          "col": 11,
          "row": 2,
          "start": 11,
          "state": 2,
          "type": "Identifier",
          "value": "i",
        },
        {
          "col": 13,
          "row": 2,
          "start": 13,
          "state": 6,
          "type": "Operators",
          "value": "=",
        },
        {
          "col": 15,
          "row": 2,
          "start": 15,
          "state": 3,
          "type": "Number",
          "value": "0",
        },
        {
          "col": 16,
          "row": 2,
          "start": 16,
          "state": 4,
          "type": "Punctuator",
          "value": ";",
        },
        {
          "col": 18,
          "row": 2,
          "start": 18,
          "state": 2,
          "type": "Identifier",
          "value": "i",
        },
        {
          "col": 20,
          "row": 2,
          "start": 20,
          "state": 6,
          "type": "Operators",
          "value": "<",
        },
        {
          "col": 22,
          "row": 2,
          "start": 22,
          "state": 3,
          "type": "Number",
          "value": "3",
        },
        {
          "col": 23,
          "row": 2,
          "start": 23,
          "state": 4,
          "type": "Punctuator",
          "value": ";",
        },
        {
          "col": 25,
          "row": 2,
          "start": 25,
          "state": 2,
          "type": "Identifier",
          "value": "i",
        },
        {
          "col": 27,
          "row": 2,
          "start": 26,
          "state": 6,
          "type": "Operators",
          "value": "++",
        },
        {
          "col": 28,
          "row": 2,
          "start": 28,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 30,
          "row": 2,
          "start": 30,
          "state": 4,
          "type": "Punctuator",
          "value": "{",
        },
        {
          "col": 32,
          "row": 2,
          "start": 31,
          "state": 5,
          "type": "Punctuator",
          "value": "rn",
        },
        {
          "col": 6,
          "row": 3,
          "start": 4,
          "state": 1,
          "type": "Keyword",
          "value": "let",
        },
        {
          "col": 8,
          "row": 3,
          "start": 8,
          "state": 2,
          "type": "Identifier",
          "value": "j",
        },
        {
          "col": 10,
          "row": 3,
          "start": 10,
          "state": 6,
          "type": "Operators",
          "value": "=",
        },
        {
          "col": 12,
          "row": 3,
          "start": 12,
          "state": 3,
          "type": "Number",
          "value": "0",
        },
        {
          "col": 14,
          "row": 3,
          "start": 13,
          "state": 5,
          "type": "Punctuator",
          "value": "rn",
        },
        {
          "col": 8,
          "row": 4,
          "start": 4,
          "state": 1,
          "type": "Keyword",
          "value": "while",
        },
        {
          "col": 10,
          "row": 4,
          "start": 10,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 11,
          "row": 4,
          "start": 11,
          "state": 2,
          "type": "Identifier",
          "value": "j",
        },
        {
          "col": 13,
          "row": 4,
          "start": 13,
          "state": 6,
          "type": "Operators",
          "value": "<",
        },
        {
          "col": 15,
          "row": 4,
          "start": 15,
          "state": 2,
          "type": "Identifier",
          "value": "i",
        },
        {
          "col": 16,
          "row": 4,
          "start": 16,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 18,
          "row": 4,
          "start": 18,
          "state": 4,
          "type": "Punctuator",
          "value": "{",
        },
        {
          "col": 20,
          "row": 4,
          "start": 19,
          "state": 5,
          "type": "Punctuator",
          "value": "rn",
        },
        {
          "col": 6,
          "row": 5,
          "start": 6,
          "state": 2,
          "type": "Identifier",
          "value": "j",
        },
        {
          "col": 8,
          "row": 5,
          "start": 7,
          "state": 6,
          "type": "Operators",
          "value": "++",
        },
        {
          "col": 10,
          "row": 5,
          "start": 9,
          "state": 5,
          "type": "Punctuator",
          "value": "rn",
        },
        {
          "col": 12,
          "row": 6,
          "start": 6,
          "state": 2,
          "type": "Identifier",
          "value": "console",
        },
        {
          "col": 13,
          "row": 6,
          "start": 13,
          "state": 6,
          "type": "Operators",
          "value": ".",
        },
        {
          "col": 16,
          "row": 6,
          "start": 14,
          "state": 2,
          "type": "Identifier",
          "value": "log",
        },
        {
          "col": 17,
          "row": 6,
          "start": 17,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 18,
          "row": 6,
          "start": 18,
          "state": 2,
          "type": "Identifier",
          "value": "j",
        },
        {
          "col": 19,
          "row": 6,
          "start": 19,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 21,
          "row": 6,
          "start": 20,
          "state": 5,
          "type": "Punctuator",
          "value": "rn",
        },
        {
          "col": 12,
          "row": 7,
          "start": 6,
          "state": 2,
          "type": "Identifier",
          "value": "console",
        },
        {
          "col": 13,
          "row": 7,
          "start": 13,
          "state": 6,
          "type": "Operators",
          "value": ".",
        },
        {
          "col": 16,
          "row": 7,
          "start": 14,
          "state": 2,
          "type": "Identifier",
          "value": "log",
        },
        {
          "col": 17,
          "row": 7,
          "start": 17,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 18,
          "row": 7,
          "start": 18,
          "state": 2,
          "type": "Identifier",
          "value": "j",
        },
        {
          "col": 20,
          "row": 7,
          "start": 20,
          "state": 6,
          "type": "Operators",
          "value": "+",
        },
        {
          "col": 29,
          "row": 7,
          "start": 22,
          "state": 7,
          "type": "String",
          "value": "\\"dawdaw\\"",
        },
        {
          "col": 31,
          "row": 7,
          "start": 31,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 33,
          "row": 7,
          "start": 32,
          "state": 5,
          "type": "Punctuator",
          "value": "rn",
        },
        {
          "col": 4,
          "row": 8,
          "start": 4,
          "state": 4,
          "type": "Punctuator",
          "value": "}",
        },
        {
          "col": 6,
          "row": 8,
          "start": 5,
          "state": 5,
          "type": "Punctuator",
          "value": "rn",
        },
        {
          "col": 2,
          "row": 9,
          "start": 2,
          "state": 4,
          "type": "Punctuator",
          "value": "}",
        },
        {
          "col": 4,
          "row": 9,
          "start": 3,
          "state": 5,
          "type": "Punctuator",
          "value": "rn",
        },
        {
          "col": 7,
          "row": 10,
          "start": 2,
          "state": 1,
          "type": "Keyword",
          "value": "return",
        },
        {
          "col": 9,
          "row": 10,
          "start": 9,
          "state": 2,
          "type": "Identifier",
          "value": "a",
        },
        {
          "col": 11,
          "row": 10,
          "start": 11,
          "state": 6,
          "type": "Operators",
          "value": ">",
        },
        {
          "col": 13,
          "row": 10,
          "start": 13,
          "state": 2,
          "type": "Identifier",
          "value": "b",
        },
        {
          "col": 15,
          "row": 10,
          "start": 15,
          "state": 6,
          "type": "Operators",
          "value": "?",
        },
        {
          "col": 17,
          "row": 10,
          "start": 17,
          "state": 3,
          "type": "Number",
          "value": "1",
        },
        {
          "col": 19,
          "row": 10,
          "start": 19,
          "state": 6,
          "type": "Operators",
          "value": ":",
        },
        {
          "col": 21,
          "row": 10,
          "start": 21,
          "state": 3,
          "type": "Number",
          "value": "2",
        },
        {
          "col": 22,
          "row": 10,
          "start": 22,
          "state": 4,
          "type": "Punctuator",
          "value": ";",
        },
        {
          "col": 25,
          "row": 10,
          "start": 24,
          "state": 5,
          "type": "Punctuator",
          "value": "rn",
        },
        {
          "col": -1,
          "row": 11,
          "start": -1,
          "state": 4,
          "type": "Punctuator",
          "value": "}",
        },
      ]
    `)
  })
})
