import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import { resolve } from 'node:path';
import { tokenize } from '../src/utils/tokensize'

describe.only('parser', async () => {

  const id = resolve(__dirname, './fixtures/source.js')
  const code = await fs.promises.readFile(id, 'utf-8')

  it('should be parser to Tooken', () => {

    expect(tokenize(code)).toMatchInlineSnapshot(`
      [
        {
          "col": 7,
          "row": 0,
          "start": 0,
          "state": 1,
          "type": "Keyword",
          "value": "function",
        },
        {
          "col": 11,
          "row": 0,
          "start": 9,
          "state": 2,
          "type": "Identifier",
          "value": "add",
        },
        {
          "col": 12,
          "row": 0,
          "start": 12,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 13,
          "row": 0,
          "start": 13,
          "state": 2,
          "type": "Identifier",
          "value": "a",
        },
        {
          "col": 14,
          "row": 0,
          "start": 14,
          "state": 4,
          "type": "Punctuator",
          "value": ",",
        },
        {
          "col": 16,
          "row": 0,
          "start": 16,
          "state": 2,
          "type": "Identifier",
          "value": "b",
        },
        {
          "col": 17,
          "row": 0,
          "start": 17,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 19,
          "row": 0,
          "start": 19,
          "state": 4,
          "type": "Punctuator",
          "value": "{",
        },
        {
          "col": 27,
          "row": 0,
          "start": 22,
          "state": 1,
          "type": "Keyword",
          "value": "return",
        },
        {
          "col": 29,
          "row": 0,
          "start": 29,
          "state": 2,
          "type": "Identifier",
          "value": "a",
        },
        {
          "col": 31,
          "row": 0,
          "start": 31,
          "state": 6,
          "type": "Operators",
          "value": "+",
        },
        {
          "col": 33,
          "row": 0,
          "start": 33,
          "state": 2,
          "type": "Identifier",
          "value": "b",
        },
        {
          "col": 34,
          "row": 0,
          "start": 34,
          "state": 4,
          "type": "Punctuator",
          "value": "}",
        },
        {
          "col": 42,
          "row": 0,
          "start": 35,
          "state": 1,
          "type": "Keyword",
          "value": "function",
        },
        {
          "col": 47,
          "row": 0,
          "start": 44,
          "state": 2,
          "type": "Identifier",
          "value": "main",
        },
        {
          "col": 48,
          "row": 0,
          "start": 48,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 49,
          "row": 0,
          "start": 49,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 51,
          "row": 0,
          "start": 51,
          "state": 4,
          "type": "Punctuator",
          "value": "{",
        },
        {
          "col": 56,
          "row": 0,
          "start": 54,
          "state": 1,
          "type": "Keyword",
          "value": "let",
        },
        {
          "col": 58,
          "row": 0,
          "start": 58,
          "state": 2,
          "type": "Identifier",
          "value": "a",
        },
        {
          "col": 60,
          "row": 0,
          "start": 60,
          "state": 6,
          "type": "Operators",
          "value": "=",
        },
        {
          "col": 62,
          "row": 0,
          "start": 62,
          "state": 3,
          "type": "Number",
          "value": "1",
        },
        {
          "col": 63,
          "row": 0,
          "start": 63,
          "state": 4,
          "type": "Punctuator",
          "value": ";",
        },
        {
          "col": 68,
          "row": 0,
          "start": 66,
          "state": 1,
          "type": "Keyword",
          "value": "let",
        },
        {
          "col": 70,
          "row": 0,
          "start": 70,
          "state": 2,
          "type": "Identifier",
          "value": "b",
        },
        {
          "col": 72,
          "row": 0,
          "start": 72,
          "state": 6,
          "type": "Operators",
          "value": "=",
        },
        {
          "col": 74,
          "row": 0,
          "start": 74,
          "state": 3,
          "type": "Number",
          "value": "2",
        },
        {
          "col": 75,
          "row": 0,
          "start": 75,
          "state": 4,
          "type": "Punctuator",
          "value": ";",
        },
        {
          "col": 83,
          "row": 0,
          "start": 78,
          "state": 1,
          "type": "Keyword",
          "value": "return",
        },
        {
          "col": 87,
          "row": 0,
          "start": 85,
          "state": 2,
          "type": "Identifier",
          "value": "add",
        },
        {
          "col": 88,
          "row": 0,
          "start": 88,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 89,
          "row": 0,
          "start": 89,
          "state": 2,
          "type": "Identifier",
          "value": "a",
        },
        {
          "col": 90,
          "row": 0,
          "start": 90,
          "state": 4,
          "type": "Punctuator",
          "value": ",",
        },
        {
          "col": 92,
          "row": 0,
          "start": 92,
          "state": 2,
          "type": "Identifier",
          "value": "b",
        },
        {
          "col": 93,
          "row": 0,
          "start": 93,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 94,
          "row": 0,
          "start": 94,
          "state": 4,
          "type": "Punctuator",
          "value": ";",
        },
        {
          "col": 95,
          "row": 0,
          "start": 95,
          "state": 4,
          "type": "Punctuator",
          "value": "}",
        },
      ]
    `)
  })
})
