import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import { resolve } from 'node:path';
import { tokenize } from '../src/utils/tokensize'

describe.only('parser', async () => {

  const id = resolve(__dirname, './fixtures/source.js')
  const code = await fs.promises.readFile(id, 'utf-8')

  it('should be parser to Tooken', () => {

    expect(tokenize(code)).toMatchInlineSnapshot(`
      [
        {
          "col": 5,
          "row": 0,
          "start": 0,
          "state": 1,
          "type": "Keyword",
          "value": "import",
        },
        {
          "col": 13,
          "row": 0,
          "start": 7,
          "state": 2,
          "type": "Identifier",
          "value": "keyword",
        },
        {
          "col": 18,
          "row": 0,
          "start": 15,
          "state": 1,
          "type": "Keyword",
          "value": "from",
        },
        {
          "col": 29,
          "row": 0,
          "start": 19,
          "state": 7,
          "type": "String",
          "value": "\\"./keyowrd\\"",
        },
        {
          "col": 36,
          "row": 0,
          "start": 31,
          "state": 1,
          "type": "Keyword",
          "value": "import",
        },
        {
          "col": 46,
          "row": 0,
          "start": 38,
          "state": 2,
          "type": "Identifier",
          "value": "operators",
        },
        {
          "col": 51,
          "row": 0,
          "start": 48,
          "state": 1,
          "type": "Keyword",
          "value": "from",
        },
        {
          "col": 64,
          "row": 0,
          "start": 52,
          "state": 7,
          "type": "String",
          "value": "'./operators'",
        },
        {
          "col": 71,
          "row": 0,
          "start": 66,
          "state": 1,
          "type": "Keyword",
          "value": "import",
        },
        {
          "col": 82,
          "row": 0,
          "start": 73,
          "state": 2,
          "type": "Identifier",
          "value": "punctuator",
        },
        {
          "col": 87,
          "row": 0,
          "start": 84,
          "state": 1,
          "type": "Keyword",
          "value": "from",
        },
        {
          "col": 101,
          "row": 0,
          "start": 88,
          "state": 7,
          "type": "String",
          "value": "'./punctuator'",
        },
        {
          "col": 110,
          "row": 0,
          "start": 103,
          "state": 1,
          "type": "Keyword",
          "value": "function",
        },
        {
          "col": 118,
          "row": 0,
          "start": 112,
          "state": 2,
          "type": "Identifier",
          "value": "isAlpha",
        },
        {
          "col": 119,
          "row": 0,
          "start": 119,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 120,
          "row": 0,
          "start": 120,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 121,
          "row": 0,
          "start": 121,
          "state": 6,
          "type": "Operators",
          "value": ":",
        },
        {
          "col": 128,
          "row": 0,
          "start": 123,
          "state": 2,
          "type": "Identifier",
          "value": "string",
        },
        {
          "col": 129,
          "row": 0,
          "start": 129,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 131,
          "row": 0,
          "start": 131,
          "state": 4,
          "type": "Punctuator",
          "value": "{",
        },
        {
          "col": 139,
          "row": 0,
          "start": 134,
          "state": 1,
          "type": "Keyword",
          "value": "return",
        },
        {
          "col": 141,
          "row": 0,
          "start": 141,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 142,
          "row": 0,
          "start": 142,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 145,
          "row": 0,
          "start": 144,
          "state": 6,
          "type": "Operators",
          "value": ">=",
        },
        {
          "col": 148,
          "row": 0,
          "start": 146,
          "state": 7,
          "type": "String",
          "value": "'a'",
        },
        {
          "col": 152,
          "row": 0,
          "start": 151,
          "state": 6,
          "type": "Operators",
          "value": "&&",
        },
        {
          "col": 154,
          "row": 0,
          "start": 154,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 157,
          "row": 0,
          "start": 156,
          "state": 6,
          "type": "Operators",
          "value": "<=",
        },
        {
          "col": 160,
          "row": 0,
          "start": 158,
          "state": 7,
          "type": "String",
          "value": "'z'",
        },
        {
          "col": 162,
          "row": 0,
          "start": 162,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 165,
          "row": 0,
          "start": 164,
          "state": 6,
          "type": "Operators",
          "value": "||",
        },
        {
          "col": 167,
          "row": 0,
          "start": 167,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 168,
          "row": 0,
          "start": 168,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 171,
          "row": 0,
          "start": 170,
          "state": 6,
          "type": "Operators",
          "value": ">=",
        },
        {
          "col": 174,
          "row": 0,
          "start": 172,
          "state": 7,
          "type": "String",
          "value": "'A'",
        },
        {
          "col": 178,
          "row": 0,
          "start": 177,
          "state": 6,
          "type": "Operators",
          "value": "&&",
        },
        {
          "col": 180,
          "row": 0,
          "start": 180,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 183,
          "row": 0,
          "start": 182,
          "state": 6,
          "type": "Operators",
          "value": "<=",
        },
        {
          "col": 186,
          "row": 0,
          "start": 184,
          "state": 7,
          "type": "String",
          "value": "'Z'",
        },
        {
          "col": 188,
          "row": 0,
          "start": 188,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 191,
          "row": 0,
          "start": 190,
          "state": 6,
          "type": "Operators",
          "value": "||",
        },
        {
          "col": 193,
          "row": 0,
          "start": 193,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 197,
          "row": 0,
          "start": 195,
          "state": 6,
          "type": "Operators",
          "value": "===",
        },
        {
          "col": 200,
          "row": 0,
          "start": 198,
          "state": 7,
          "type": "String",
          "value": "'_'",
        },
        {
          "col": 202,
          "row": 0,
          "start": 202,
          "state": 4,
          "type": "Punctuator",
          "value": "}",
        },
        {
          "col": 210,
          "row": 0,
          "start": 203,
          "state": 1,
          "type": "Keyword",
          "value": "function",
        },
        {
          "col": 218,
          "row": 0,
          "start": 212,
          "state": 2,
          "type": "Identifier",
          "value": "isDigit",
        },
        {
          "col": 219,
          "row": 0,
          "start": 219,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 220,
          "row": 0,
          "start": 220,
          "state": 2,
          "type": "Identifier",
          "value": "d",
        },
        {
          "col": 221,
          "row": 0,
          "start": 221,
          "state": 6,
          "type": "Operators",
          "value": ":",
        },
        {
          "col": 228,
          "row": 0,
          "start": 223,
          "state": 2,
          "type": "Identifier",
          "value": "string",
        },
        {
          "col": 229,
          "row": 0,
          "start": 229,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 231,
          "row": 0,
          "start": 231,
          "state": 4,
          "type": "Punctuator",
          "value": "{",
        },
        {
          "col": 239,
          "row": 0,
          "start": 234,
          "state": 1,
          "type": "Keyword",
          "value": "return",
        },
        {
          "col": 241,
          "row": 0,
          "start": 241,
          "state": 2,
          "type": "Identifier",
          "value": "d",
        },
        {
          "col": 244,
          "row": 0,
          "start": 243,
          "state": 6,
          "type": "Operators",
          "value": ">=",
        },
        {
          "col": 247,
          "row": 0,
          "start": 245,
          "state": 7,
          "type": "String",
          "value": "'0'",
        },
        {
          "col": 251,
          "row": 0,
          "start": 250,
          "state": 6,
          "type": "Operators",
          "value": "&&",
        },
        {
          "col": 253,
          "row": 0,
          "start": 253,
          "state": 2,
          "type": "Identifier",
          "value": "d",
        },
        {
          "col": 256,
          "row": 0,
          "start": 255,
          "state": 6,
          "type": "Operators",
          "value": "<=",
        },
        {
          "col": 259,
          "row": 0,
          "start": 257,
          "state": 7,
          "type": "String",
          "value": "'9'",
        },
        {
          "col": 261,
          "row": 0,
          "start": 261,
          "state": 4,
          "type": "Punctuator",
          "value": "}",
        },
        {
          "col": 269,
          "row": 0,
          "start": 262,
          "state": 1,
          "type": "Keyword",
          "value": "function",
        },
        {
          "col": 277,
          "row": 0,
          "start": 271,
          "state": 2,
          "type": "Identifier",
          "value": "isSpace",
        },
        {
          "col": 278,
          "row": 0,
          "start": 278,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 279,
          "row": 0,
          "start": 279,
          "state": 2,
          "type": "Identifier",
          "value": "s",
        },
        {
          "col": 280,
          "row": 0,
          "start": 280,
          "state": 6,
          "type": "Operators",
          "value": ":",
        },
        {
          "col": 287,
          "row": 0,
          "start": 282,
          "state": 2,
          "type": "Identifier",
          "value": "string",
        },
        {
          "col": 288,
          "row": 0,
          "start": 288,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 290,
          "row": 0,
          "start": 290,
          "state": 4,
          "type": "Punctuator",
          "value": "{",
        },
        {
          "col": 298,
          "row": 0,
          "start": 293,
          "state": 1,
          "type": "Keyword",
          "value": "return",
        },
        {
          "col": 300,
          "row": 0,
          "start": 300,
          "state": 2,
          "type": "Identifier",
          "value": "s",
        },
        {
          "col": 304,
          "row": 0,
          "start": 302,
          "state": 6,
          "type": "Operators",
          "value": "===",
        },
        {
          "col": 307,
          "row": 0,
          "start": 305,
          "state": 7,
          "type": "String",
          "value": "' '",
        },
        {
          "col": 309,
          "row": 0,
          "start": 309,
          "state": 4,
          "type": "Punctuator",
          "value": "}",
        },
        {
          "col": 317,
          "row": 0,
          "start": 310,
          "state": 1,
          "type": "Keyword",
          "value": "function",
        },
        {
          "col": 330,
          "row": 0,
          "start": 319,
          "state": 2,
          "type": "Identifier",
          "value": "isPunctuator",
        },
        {
          "col": 331,
          "row": 0,
          "start": 331,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 332,
          "row": 0,
          "start": 332,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 333,
          "row": 0,
          "start": 333,
          "state": 6,
          "type": "Operators",
          "value": ":",
        },
        {
          "col": 340,
          "row": 0,
          "start": 335,
          "state": 2,
          "type": "Identifier",
          "value": "string",
        },
        {
          "col": 341,
          "row": 0,
          "start": 341,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 343,
          "row": 0,
          "start": 343,
          "state": 4,
          "type": "Punctuator",
          "value": "{",
        },
        {
          "col": 351,
          "row": 0,
          "start": 346,
          "state": 1,
          "type": "Keyword",
          "value": "return",
        },
        {
          "col": 371,
          "row": 0,
          "start": 353,
          "state": 2,
          "type": "Identifier",
          "value": "punctuator.includes",
        },
        {
          "col": 372,
          "row": 0,
          "start": 372,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 373,
          "row": 0,
          "start": 373,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 374,
          "row": 0,
          "start": 374,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 375,
          "row": 0,
          "start": 375,
          "state": 4,
          "type": "Punctuator",
          "value": "}",
        },
        {
          "col": 383,
          "row": 0,
          "start": 376,
          "state": 1,
          "type": "Keyword",
          "value": "function",
        },
        {
          "col": 395,
          "row": 0,
          "start": 385,
          "state": 2,
          "type": "Identifier",
          "value": "isOperators",
        },
        {
          "col": 396,
          "row": 0,
          "start": 396,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 397,
          "row": 0,
          "start": 397,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 398,
          "row": 0,
          "start": 398,
          "state": 6,
          "type": "Operators",
          "value": ":",
        },
        {
          "col": 405,
          "row": 0,
          "start": 400,
          "state": 2,
          "type": "Identifier",
          "value": "string",
        },
        {
          "col": 406,
          "row": 0,
          "start": 406,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 408,
          "row": 0,
          "start": 408,
          "state": 4,
          "type": "Punctuator",
          "value": "{",
        },
        {
          "col": 416,
          "row": 0,
          "start": 411,
          "state": 1,
          "type": "Keyword",
          "value": "return",
        },
        {
          "col": 435,
          "row": 0,
          "start": 418,
          "state": 2,
          "type": "Identifier",
          "value": "operators.includes",
        },
        {
          "col": 436,
          "row": 0,
          "start": 436,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 437,
          "row": 0,
          "start": 437,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 438,
          "row": 0,
          "start": 438,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 439,
          "row": 0,
          "start": 439,
          "state": 4,
          "type": "Punctuator",
          "value": "}",
        },
        {
          "col": 447,
          "row": 0,
          "start": 440,
          "state": 1,
          "type": "Keyword",
          "value": "function",
        },
        {
          "col": 457,
          "row": 0,
          "start": 449,
          "state": 2,
          "type": "Identifier",
          "value": "isKeyword",
        },
        {
          "col": 458,
          "row": 0,
          "start": 458,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 459,
          "row": 0,
          "start": 459,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 460,
          "row": 0,
          "start": 460,
          "state": 6,
          "type": "Operators",
          "value": ":",
        },
        {
          "col": 467,
          "row": 0,
          "start": 462,
          "state": 2,
          "type": "Identifier",
          "value": "string",
        },
        {
          "col": 468,
          "row": 0,
          "start": 468,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 470,
          "row": 0,
          "start": 470,
          "state": 4,
          "type": "Punctuator",
          "value": "{",
        },
        {
          "col": 478,
          "row": 0,
          "start": 473,
          "state": 1,
          "type": "Keyword",
          "value": "return",
        },
        {
          "col": 495,
          "row": 0,
          "start": 480,
          "state": 2,
          "type": "Identifier",
          "value": "keyword.includes",
        },
        {
          "col": 496,
          "row": 0,
          "start": 496,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 497,
          "row": 0,
          "start": 497,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 498,
          "row": 0,
          "start": 498,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 499,
          "row": 0,
          "start": 499,
          "state": 4,
          "type": "Punctuator",
          "value": "}",
        },
        {
          "col": 507,
          "row": 0,
          "start": 500,
          "state": 1,
          "type": "Keyword",
          "value": "function",
        },
        {
          "col": 513,
          "row": 0,
          "start": 509,
          "state": 2,
          "type": "Identifier",
          "value": "isOct",
        },
        {
          "col": 514,
          "row": 0,
          "start": 514,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 515,
          "row": 0,
          "start": 515,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 516,
          "row": 0,
          "start": 516,
          "state": 6,
          "type": "Operators",
          "value": ":",
        },
        {
          "col": 523,
          "row": 0,
          "start": 518,
          "state": 2,
          "type": "Identifier",
          "value": "string",
        },
        {
          "col": 524,
          "row": 0,
          "start": 524,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 526,
          "row": 0,
          "start": 526,
          "state": 4,
          "type": "Punctuator",
          "value": "{",
        },
        {
          "col": 534,
          "row": 0,
          "start": 529,
          "state": 1,
          "type": "Keyword",
          "value": "return",
        },
        {
          "col": 536,
          "row": 0,
          "start": 536,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 539,
          "row": 0,
          "start": 538,
          "state": 6,
          "type": "Operators",
          "value": ">=",
        },
        {
          "col": 542,
          "row": 0,
          "start": 540,
          "state": 7,
          "type": "String",
          "value": "'0'",
        },
        {
          "col": 546,
          "row": 0,
          "start": 545,
          "state": 6,
          "type": "Operators",
          "value": "&&",
        },
        {
          "col": 548,
          "row": 0,
          "start": 548,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 551,
          "row": 0,
          "start": 550,
          "state": 6,
          "type": "Operators",
          "value": "<=",
        },
        {
          "col": 554,
          "row": 0,
          "start": 552,
          "state": 7,
          "type": "String",
          "value": "'7'",
        },
        {
          "col": 556,
          "row": 0,
          "start": 556,
          "state": 4,
          "type": "Punctuator",
          "value": "}",
        },
        {
          "col": 564,
          "row": 0,
          "start": 557,
          "state": 1,
          "type": "Keyword",
          "value": "function",
        },
        {
          "col": 568,
          "row": 0,
          "start": 566,
          "state": 2,
          "type": "Identifier",
          "value": "isE",
        },
        {
          "col": 569,
          "row": 0,
          "start": 569,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 570,
          "row": 0,
          "start": 570,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 571,
          "row": 0,
          "start": 571,
          "state": 6,
          "type": "Operators",
          "value": ":",
        },
        {
          "col": 578,
          "row": 0,
          "start": 573,
          "state": 2,
          "type": "Identifier",
          "value": "string",
        },
        {
          "col": 579,
          "row": 0,
          "start": 579,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 581,
          "row": 0,
          "start": 581,
          "state": 4,
          "type": "Punctuator",
          "value": "{",
        },
        {
          "col": 589,
          "row": 0,
          "start": 584,
          "state": 1,
          "type": "Keyword",
          "value": "return",
        },
        {
          "col": 591,
          "row": 0,
          "start": 591,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 595,
          "row": 0,
          "start": 593,
          "state": 6,
          "type": "Operators",
          "value": "===",
        },
        {
          "col": 598,
          "row": 0,
          "start": 596,
          "state": 7,
          "type": "String",
          "value": "'e'",
        },
        {
          "col": 602,
          "row": 0,
          "start": 601,
          "state": 6,
          "type": "Operators",
          "value": "||",
        },
        {
          "col": 604,
          "row": 0,
          "start": 604,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 608,
          "row": 0,
          "start": 606,
          "state": 6,
          "type": "Operators",
          "value": "===",
        },
        {
          "col": 611,
          "row": 0,
          "start": 609,
          "state": 7,
          "type": "String",
          "value": "'E'",
        },
        {
          "col": 613,
          "row": 0,
          "start": 613,
          "state": 4,
          "type": "Punctuator",
          "value": "}",
        },
        {
          "col": 621,
          "row": 0,
          "start": 614,
          "state": 1,
          "type": "Keyword",
          "value": "function",
        },
        {
          "col": 627,
          "row": 0,
          "start": 623,
          "state": 2,
          "type": "Identifier",
          "value": "isHex",
        },
        {
          "col": 628,
          "row": 0,
          "start": 628,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 629,
          "row": 0,
          "start": 629,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 630,
          "row": 0,
          "start": 630,
          "state": 6,
          "type": "Operators",
          "value": ":",
        },
        {
          "col": 637,
          "row": 0,
          "start": 632,
          "state": 2,
          "type": "Identifier",
          "value": "string",
        },
        {
          "col": 638,
          "row": 0,
          "start": 638,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 640,
          "row": 0,
          "start": 640,
          "state": 4,
          "type": "Punctuator",
          "value": "{",
        },
        {
          "col": 648,
          "row": 0,
          "start": 643,
          "state": 1,
          "type": "Keyword",
          "value": "return",
        },
        {
          "col": 650,
          "row": 0,
          "start": 650,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 651,
          "row": 0,
          "start": 651,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 654,
          "row": 0,
          "start": 653,
          "state": 6,
          "type": "Operators",
          "value": ">=",
        },
        {
          "col": 657,
          "row": 0,
          "start": 655,
          "state": 7,
          "type": "String",
          "value": "'a'",
        },
        {
          "col": 661,
          "row": 0,
          "start": 660,
          "state": 6,
          "type": "Operators",
          "value": "&&",
        },
        {
          "col": 663,
          "row": 0,
          "start": 663,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 666,
          "row": 0,
          "start": 665,
          "state": 6,
          "type": "Operators",
          "value": "<=",
        },
        {
          "col": 669,
          "row": 0,
          "start": 667,
          "state": 7,
          "type": "String",
          "value": "'f'",
        },
        {
          "col": 671,
          "row": 0,
          "start": 671,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 674,
          "row": 0,
          "start": 673,
          "state": 6,
          "type": "Operators",
          "value": "||",
        },
        {
          "col": 676,
          "row": 0,
          "start": 676,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 677,
          "row": 0,
          "start": 677,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 680,
          "row": 0,
          "start": 679,
          "state": 6,
          "type": "Operators",
          "value": ">=",
        },
        {
          "col": 683,
          "row": 0,
          "start": 681,
          "state": 7,
          "type": "String",
          "value": "'A'",
        },
        {
          "col": 687,
          "row": 0,
          "start": 686,
          "state": 6,
          "type": "Operators",
          "value": "&&",
        },
        {
          "col": 689,
          "row": 0,
          "start": 689,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 692,
          "row": 0,
          "start": 691,
          "state": 6,
          "type": "Operators",
          "value": "<=",
        },
        {
          "col": 695,
          "row": 0,
          "start": 693,
          "state": 7,
          "type": "String",
          "value": "'F'",
        },
        {
          "col": 697,
          "row": 0,
          "start": 697,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 698,
          "row": 0,
          "start": 698,
          "state": 4,
          "type": "Punctuator",
          "value": "}",
        },
        {
          "col": 706,
          "row": 0,
          "start": 699,
          "state": 1,
          "type": "Keyword",
          "value": "function",
        },
        {
          "col": 710,
          "row": 0,
          "start": 708,
          "state": 2,
          "type": "Identifier",
          "value": "isX",
        },
        {
          "col": 711,
          "row": 0,
          "start": 711,
          "state": 4,
          "type": "Punctuator",
          "value": "(",
        },
        {
          "col": 712,
          "row": 0,
          "start": 712,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 713,
          "row": 0,
          "start": 713,
          "state": 6,
          "type": "Operators",
          "value": ":",
        },
        {
          "col": 720,
          "row": 0,
          "start": 715,
          "state": 2,
          "type": "Identifier",
          "value": "string",
        },
        {
          "col": 721,
          "row": 0,
          "start": 721,
          "state": 4,
          "type": "Punctuator",
          "value": ")",
        },
        {
          "col": 723,
          "row": 0,
          "start": 723,
          "state": 4,
          "type": "Punctuator",
          "value": "{",
        },
        {
          "col": 731,
          "row": 0,
          "start": 726,
          "state": 1,
          "type": "Keyword",
          "value": "return",
        },
        {
          "col": 733,
          "row": 0,
          "start": 733,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 737,
          "row": 0,
          "start": 735,
          "state": 6,
          "type": "Operators",
          "value": "===",
        },
        {
          "col": 740,
          "row": 0,
          "start": 738,
          "state": 7,
          "type": "String",
          "value": "'x'",
        },
        {
          "col": 744,
          "row": 0,
          "start": 743,
          "state": 6,
          "type": "Operators",
          "value": "||",
        },
        {
          "col": 746,
          "row": 0,
          "start": 746,
          "state": 2,
          "type": "Identifier",
          "value": "c",
        },
        {
          "col": 750,
          "row": 0,
          "start": 748,
          "state": 6,
          "type": "Operators",
          "value": "===",
        },
        {
          "col": 753,
          "row": 0,
          "start": 751,
          "state": 7,
          "type": "String",
          "value": "'X'",
        },
        {
          "col": 755,
          "row": 0,
          "start": 755,
          "state": 4,
          "type": "Punctuator",
          "value": "}",
        },
        {
          "col": 761,
          "row": 0,
          "start": 756,
          "state": 1,
          "type": "Keyword",
          "value": "export",
        },
        {
          "col": 763,
          "row": 0,
          "start": 763,
          "state": 4,
          "type": "Punctuator",
          "value": "{",
        },
        {
          "col": 772,
          "row": 0,
          "start": 766,
          "state": 2,
          "type": "Identifier",
          "value": "isAlpha",
        },
        {
          "col": 773,
          "row": 0,
          "start": 773,
          "state": 4,
          "type": "Punctuator",
          "value": ",",
        },
        {
          "col": 782,
          "row": 0,
          "start": 776,
          "state": 2,
          "type": "Identifier",
          "value": "isDigit",
        },
        {
          "col": 783,
          "row": 0,
          "start": 783,
          "state": 4,
          "type": "Punctuator",
          "value": ",",
        },
        {
          "col": 792,
          "row": 0,
          "start": 786,
          "state": 2,
          "type": "Identifier",
          "value": "isSpace",
        },
        {
          "col": 793,
          "row": 0,
          "start": 793,
          "state": 4,
          "type": "Punctuator",
          "value": ",",
        },
        {
          "col": 807,
          "row": 0,
          "start": 796,
          "state": 2,
          "type": "Identifier",
          "value": "isPunctuator",
        },
        {
          "col": 808,
          "row": 0,
          "start": 808,
          "state": 4,
          "type": "Punctuator",
          "value": ",",
        },
        {
          "col": 821,
          "row": 0,
          "start": 811,
          "state": 2,
          "type": "Identifier",
          "value": "isOperators",
        },
        {
          "col": 822,
          "row": 0,
          "start": 822,
          "state": 4,
          "type": "Punctuator",
          "value": ",",
        },
        {
          "col": 833,
          "row": 0,
          "start": 825,
          "state": 2,
          "type": "Identifier",
          "value": "isKeyword",
        },
        {
          "col": 834,
          "row": 0,
          "start": 834,
          "state": 4,
          "type": "Punctuator",
          "value": ",",
        },
        {
          "col": 841,
          "row": 0,
          "start": 837,
          "state": 2,
          "type": "Identifier",
          "value": "isOct",
        },
        {
          "col": 842,
          "row": 0,
          "start": 842,
          "state": 4,
          "type": "Punctuator",
          "value": ",",
        },
        {
          "col": 849,
          "row": 0,
          "start": 845,
          "state": 2,
          "type": "Identifier",
          "value": "isHex",
        },
        {
          "col": 850,
          "row": 0,
          "start": 850,
          "state": 4,
          "type": "Punctuator",
          "value": ",",
        },
        {
          "col": 855,
          "row": 0,
          "start": 853,
          "state": 2,
          "type": "Identifier",
          "value": "isX",
        },
        {
          "col": 856,
          "row": 0,
          "start": 856,
          "state": 4,
          "type": "Punctuator",
          "value": ",",
        },
        {
          "col": 861,
          "row": 0,
          "start": 859,
          "state": 2,
          "type": "Identifier",
          "value": "isE",
        },
        {
          "col": 862,
          "row": 0,
          "start": 862,
          "state": 4,
          "type": "Punctuator",
          "value": "}",
        },
      ]
    `)
  })
})
